const paths = {
  DASHBOARD: "/",
  CV_CREATOR: "/cvEditor",
  CV_EDITOR: "/cvEditor/:id",
  REGISTER: "/newAccount/",
  REGISTER_ADMIN: "/newAccount/:role(staff)",
  FOOTER: "/footer",
  LOGIN: "/login",
  USER: "/user",
  OFFER_FORM: "/offerForm/:id?",
  JOB_OFFERS: "/jobOffers",
  CV_APPROVAL: "/cvApproval",
  MY_OFFERS: "/myOffers",
  CONTACT_PAGE: "/contact",
  BLOG_POST: "/blog/blogpost/:id",
  BLOG_PAGE: "/blog",
  BLOG_PAGE_FILTERED: "/blog/:cat",
  BLOG_FORM: "/blog/newPost",
  BLOG_EDIT: "/blog/newPost/:id",
  JOB_OFFER_DETAILS: "/jobOffers/:id",
  MY_CVS: "/myCVs",
  USER_APPROVAL: "/userApproval",
  CV_CORRECTION: "/cvCorrection/:id",
  STEPS: "/steps",
  CHATS: "/chats",
  CHAT_DETAILS: "/chats/:id",
  USER_LIST: "/userList",
  OFFER_APPROVAL: "/offerApproval",
  CHANGE_DATA: "/changeData/:id",
  PASSWORD_RESET: "/newPassword",
  NEW_PASSWORD: "/newPassword/:id",
  POLICIES: "/regulations/:doc",
};
export { paths };
